// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Send(arg1) {
  return window['go']['main']['App']['Send'](arg1);
}

export function Start(arg1, arg2) {
  return window['go']['main']['App']['Start'](arg1, arg2);
}
