// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Send(arg1:string):Promise<void>;

export function Start(arg1:string,arg2:string):Promise<void>;
